helloidol/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    #함수뒤 괄호가 없음
    path('playground/', include('playground.urls')),
    path('kda/', include('kda.urls')),
    # path('playground/hello/', playground.views.say_hello, name='playground_hello'),
    # path('playground/hello_html/', playground.views.say_hello_html, name='playground_hello_html'),
    path('admin/', admin.site.urls),
]

kda/urls.py
from django.urls import path

from kda import views

app_name='kda'

urlpatterns =[
    path('멤버리스트/',views.show_멤버리스트, name='멤버리스트'),
    path('<멤버>/',views.show_멤버, name='멤버'),
   # path('ari/',views.show_ari, name='ari'),
   # path('akali/',views.show_akali, name='akali'),
]

playground/urls.py
from django.urls import path

from playground import views

app_name = 'playground'

urlpatterns = [
    path('hello/', views.say_hello, name='hello'),  # {% url 'playground:hello' %}
    path('hello_html/', views.say_hello_html, name='hello_html'),  # {% url 'playground:hello_html' %}
    path('bye_html/', views.say_bye_html, name='bye_html'),  # {% url 'playground:bye_html' %}
]

kda/models.py
from django.db import models

# Create your models here.

playground/views.py
from django.http import HttpResponse
from django.shortcuts import render

def say_hello(reguest):
    return HttpResponse("Hello World!")

def say_hello_html(request):
    return render(request, 'playground/hello.html', {'name' : '지우야 ','greeting': '안녕'})

def say_bye_html(request):
    context ={
        'singer' : '아리아나 그란데',
        'title' : 'bye',
    }
    return render(request, 'playground/bye.html', context=context)

kda/templates/kda/akali.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Akali</title>
</head>
<body>
    <h1>kda</h1>
    <h2>Akali</h2>
    <img src="https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt9e3ffdcedbc7bb90/5f4041c113ba7e23cc5b6754/AkaliTeaserImage_16_9.jpg?quality=90&crop=1%3A1&width=600" style="border-radius:50%">
</body>
</html>

kda/templates/kda/ari.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ari</title>
</head>
<body>
<h1>kda</h1>
<h2>Ari</h2>
<img src="https://media.bunjang.co.kr/product/200514473_1_1675936339_w%7Bres%7D.jpg"/>
</body>
</html>

kda/templates/kda/멤버.html
{% extends 'base.html' %}

{% block title %}{{ group_name }} - {{ name }}{% endblock %}

{% block content %}
    <a href="{% url 'kda:멤버리스트' %}">멤버리스트️</a>
    <h1>{{ group_name }}</h1>
    <h2>{{ name }}</h2>

    {%  load static %}
    <img src="{% static img_src %}" alt="" style="border-radius:50%">
{% endblock %}

kda/templates/kda/멤버리스트.html
{#{{ members }}#}
{% extends 'base.html' %}
{%  block title %}kda - 멤버리스트{% endblock %}

{% block content %}
<h1>{{ members.0.group_name }} - 멤버리스트</h1>
<table  class="table">
    <tr>
         <th>이름 https</th>
         <th>이름 ../</th>
         <th>이름 /</th>
         <th>이름 django</th>
         <th>프로필</th>
    </tr>
{# members에서 하나씩 꺼내어 member에 넣자 #}
{% for member in members %}
    <tr>
        {# 멤버이름에 링크: kda/{{member.name}}   #}
{#        <td>{{ member.name }}</td>#}
        <td><a href="//http://localhost:8000/kda/{{ member.name }}/">{{ member.name }}</a> //: 인터넷 절대 </td>
        <td><a href="../../kda/{{ member.name }}/">{{ member.name }}</a> ../../: 부모/부모/주소(상대) </td>
        <td><a href="/kda/{{ member.name }}/">{{ member.name }}</a> / : 호스트 루트(호스트 절대) </td>
        <td><a href="{% url 'kda:멤버' 멤버=member.name %}">{{ member.name }}</a> </td>
        {% load static %}
        <td><img src="{% static member.img_src %}" alt="" style="height: 100px; border-radius: 50%;"></td>
    </tr>
{% endfor %}
</table>

{% endblock %}